### ISSUE TITLE
Cannot set the primary contact person for a contact

### ISSUE THREAD

**Issue by dlevis** [zoho/books-java-wrappers#1]
I'm trying to use the java wrapper to create a new Contact along with a primary ContactPerson. The Contact and ContactPerson get created, but I cannot set the ContactPerson as the primary contact. I've tried both using `ContactPerson.setIsPrimaryContact(true)` and using `Contact.setPrimaryContactId()` but it doesn't work. The ContactPerson is not set as the primary contact.

**Comment by SahayaRamesh** [comment]
Sorry for the inconvenience caused. We have missed handling the method `ContactPerson.setIsPrimaryContact(true)` in our side. The case is now handled. Could you please download the latest jar and retry the same?

**Comment by dlevis** [comment]
I just tried it and it works as expected. Thank you for the quick resolution. Just a small suggestion:  maybe next time it would be better to update the version number in the jar name to avoid confusion. Some build systems may also rely on that to handle library updates.
