### ISSUE TITLE
Error when trying to send invoice by email

### ISSUE THREAD

**Issue by dlevis** [zoho/books-java-wrappers#2]
I'm trying to send an existing invoice by email using the API (the invoice is already marked as sent and also has a payment, so I'm actually trying to resend it).

I've tried to call `InvoicesApi.sendEmail()` with a `null` Email object. If I understand the javadoc correctly, it should send an email with the default content. The javadoc says: *"If the Email object is not inputted, mail will be send with default mail content"* Here's my code:

```java
HashMap<String, Object> paramMap = new HashMap<String, Object>();
paramMap.put("send_attachment", true);
String emailResponse = invoicesApi.sendEmail(myInvoiceId, null, paramMap);
````

However this results in this error because it expects the Email object not to be null:

```
java.lang.NullPointerException: null
        at com.zoho.books.api.InvoicesApi.sendEmail(InvoicesApi.java:466) ~[books-java-1.0.jar:na]
```

So I've tried to define an Email object with basic values, but it also fails because it seems to expect an attachment to be defined:
```
java.lang.NullPointerException: null
        at com.zoho.books.api.InvoicesApi.sendEmail(InvoicesApi.java:470) ~[books-java-1.0.jar:na]
```

But I don't want to define an additional attachment since I've already set "send_attachment" to true in the paramMap.

I'm not sure if this is a bug or if there's something I'm not getting. I've also tried using `InvoicesApi.sendEmailInvoices()` but ran into other issues.

**Comment by SahayaRamesh** [comment]
Sorry for the inconvenience caused. We have an issue in passing an email object and attachment as null. The issue is now fixed and updated. Moreover, we recommend you not to send null values for the objects containing mandatory fields. Please download the latest jar and try the same. Thank you for your patience and kind understanding.

**Comment by dlevis** [comment]
I tested it and it now works as expected. Thank you very much.
