### ISSUE TITLE
Contact.setTaxable(false) is ignored when creating a Contact

### ISSUE THREAD

**Issue by dlevis** [zoho/books-java-wrappers#3]
When creating a Contact through the API, I set `contact.setTaxable(false)`. But when I look at the resulting Contact in the Zoho UI, the Tax Preference field is set to Taxable. The value passed to `setTaxable()` seems to be ignored.

**Comment by MuthuGanapathy** [comment]
Hi Dlevis, we have cleared the issue now.. Can you check once again and update here...

**Comment by dlevis** [comment]
Now works as expected. Thank you.
