### ISSUE TITLE
InvoiceNumber is ignored when creating a new Invoice

### ISSUE THREAD

**Issue by dlevis** [zoho/books-java-wrappers#4]
If I create an invoice through the API without setting the Invoice Number, it works fine and an invoice number is automatically generated. However if I want to create an invoice with a specific Invoice Number, the Invoice Number seems to be ignored. For example, when I try this code:

```java
Invoice invoice = new Invoice();
invoice .setInvoiceNumber("Test-001");
// Setting other invoice fields here
HashMap<String, Object> paramMap = new HashMap<String, Object>();
paramMap.put("ignore_auto_number_generation", "true");
invoicesApi.create(invoice, paramMap);
```
It returns this error:

    com.zoho.books.exception.BooksException: You cannot proceed if the Invoice Number field is blank. Enter a valid Invoice Number.

It looks like the Invoice Number is not sent with the request.

**Comment by SahayaRamesh** [comment]
Hi Dlevis, As we did not set the invoice number in the request body, the issue occurred. Now it is fixed and working fine. Could you please check with the latest jar?

**Comment by dlevis** [comment]
It works with the latest jar. Thank you.
