### ISSUE TITLE
Line items with a negative rate are ignored when creating invoice

### ISSUE THREAD

**Issue by dlevis** [zoho/books-java-wrappers#5]
If I create an invoice containing line items having a negative rate, these items are ignored and are not present in the resulting invoice. For example when I run the following code, only the first line item will be present in the invoice, the second one will be ignored.

```java
Invoice invoice = new Invoice();
...
List<LineItem> lineItems = new ArrayList<LineItem>();

LineItem lineItem1 = new LineItem();
lineItem1.setName("Item 1");
lineItem1.setRate(100);
lineItem1.setAmount(1);
lineItems.add(lineItem1);

LineItem lineItem2 = new LineItem();
lineItem2.setName("Item 2");
lineItem2.setRate(-50);
lineItem2.setAmount(1);
lineItems.add(lineItem2);

invoice.setLineItems(lineItems);

invoicesApi.create(invoice, null);
```

I know that I can use `lineItem.setDiscount()` to create line items that are discounts, but then they will show up as discounts in the Zoho reports and that is not what I want. I my case the negative line item represents a credit for something already paid, not a discount.

I get the desired result if I create the invoice through the Zoho UI. It allows me to enter items with a negative rate that are not discounts. I would like to do the same through the API. Is there a way to do that?

**Comment by SahayaRamesh** [comment]
Hi Dlevis, the above issue got fixed. Could you please check with the latest jar?

**Comment by dlevis** [comment]
It works. Thank you.
