### ISSUE TITLE
Error when creating a customer payment in a different currency without specifying an exchange rate

### ISSUE THREAD

**Issue by dlevis** [zoho/books-java-wrappers#6]
The default currency in our Zoho org is CAD but we have many clients (or contacts) for which we set the currency to USD. When I create a customer payment through the UI for an invoice in USD, it uses the current exchange rate by default and I don't have to explicitly specify one. However when I try to do the same through the API it returns this error: "Please enter a valid exchange rate". I think it should use the current exchange rate by default. I create the payment using CustomerPaymentsApi.create().

I'm pretty sure this bug was introduced by the previous commit for issue #5 because this was working fine before. I've noticed that before b4af198e641d924deae989b37183af21fe1c4d47 the exchange rate was only sent in the JSON when `exchangeRate > 0` but that condition has been removed so now it is sent all the time, and it looks like this prevents the current exchange rate from being used.

If I may provide a suggestion, maybe beans like the CustomerPayment class should use object wrappers for fields instead of primitive types (e.g. `Double` instead of `double`). This would allow to distinguish between a null (value not set) and a zero. Just my two cents.

**Comment by SahayaRamesh** [comment]
Hi Dlevis, thanks for the suggestion I will correct it later. Now the issue got fixed with `exchangeRate > 0` condition and updated here. Please check with the latest jar.

**Comment by dlevis** [comment]
It works. Thank you.
