### ISSUE TITLE
When creating a customer payment in a different currency, it does not use the current exchange rate

### ISSUE THREAD

**Issue by dlevis** [zoho/books-java-wrappers#7]
The default currency in our Zoho org is CAD but we have many clients (or contacts) for which we set the currency to USD. When I create a customer payment through the UI for an invoice in USD, it uses the current exchange rate. However when I do the same through the API, the payment is created with an exchange rate of 1 instead of the actual rate. I create the payment using CustomerPaymentsApi.create(). Why is it using 1 instead of the actual exchange rate?

**Comment by SahayaRamesh** [comment]
Hi dlevis, As I discussed with the team member he said that, 'We didn't support automatic feeds in api. Only if there any prepopulated values in memcache for the date it will be filled.We will be supporting it in future'. Hope this will helps you.

**Comment by dlevis** [comment]
This issue is not about automatic feeds. It also occurs when automatic feeds are disabled.

**Comment by OpenFalcons** [comment]
Please check whether you have configured 'Exchange Rates' for the currency.
If you are still getting the error, please write us to support@zohobooks.com. So that we will assist you in this regards.


Regards,
Muthu Ganapathy,
Zoho Books.

**Comment by SahayaRamesh** [comment]
Please check whether you have configured 'Exchange Rates' for the currency.
If you are still getting the error, please write us to support@zohobooks.com. So that we will assist you in this regards.

**Comment by dlevis** [comment]
Yes, exchange rates are configured and it works fine when I use the UI. I only get this issue when using the API.

**Comment by SahayaRamesh** [comment]
Sorry dlevis, Issue from our end.. will fix in the next update.

**Comment by dlevis** [comment]
Got a reply from Zoho support saying that the issue has been fixed. I tried it and it now works as expected. Thank you.
